### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by ivissie** [angusmcleod/discourse-layouts#1]
Hi,

There is a script error with the filter added.

filterArr = filterMode.split('/');

In the sidebar-edits.js file

![image](https://cloud.githubusercontent.com/assets/4920420/23745493/18f8d894-04c1-11e7-8cc6-676952f6ce90.png)

![image](https://cloud.githubusercontent.com/assets/4920420/23745503/22e05b2a-04c1-11e7-8988-33e6766f6981.png)

**Comment by angusmcleod** [comment]
This was fixed some time ago.
