### ISSUE TITLE
Layouts causing problems with theme-compile/view

### ISSUE THREAD

**Issue by exetico** [angusmcleod/discourse-layouts#3]
Layouts-plugin is breaking the theme. When selecting the black theme, most of the things is messed up.

Just tested with - and without the Layouts plugin locally, but also at your site by changing to the black theme.
![image](https://user-images.githubusercontent.com/3549445/30511192-164ace8c-9ad4-11e7-8a95-74719a0827e1.png)

**Comment by angusmcleod** [comment]
Fixed: https://github.com/angusmcleod/discourse-layouts/commit/dc24d1cfe04c6e60dab7bc30052801e0ace0ab9a

**Comment by exetico** [comment]
Thanks!

Wow. I don't want to comment on how i missed that minor detail.
